FROM node:18-alpine

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# copying all the files from your file system to container file system
COPY package.json .

# install all dependencies
RUN npm install

# copy outer files as well
COPY ./ .

#expose the port
EXPOSE 3001

# command to run when instantiate an image
CMD ["npm","run","dev"]
